# -*- coding: utf-8 -*-
"""conversionBinaria.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gt763iKtaZqgckhXlVdPqt75BnTUQVAr
"""

#Análisis básico del algoritmo
#Costo relativo: Cada carácter se procesa una vez, por lo que el tiempo de ejecución es lineal
#donde n es la cantidad de dígitos del binario.

#Conjuntos de datos para probar: Texto vacío, números binarios cortos, largos, con ceros en medio, y solo ceros.

#Análisis a priori: Sabemos que el tiempo de cálculo crece linealmente con el tamaño del binario,
#Análisis a posteriori: Cuando el programa se ejecuta realmente con números grandes, se confirma que tiempo
# y memoria usados también crecen proporcionalmente.
def binario_a_decimal(binario):
    decimal = 0
    potencia = 1  # 2^0
    i = len(binario) - 1

    while i >= 0:
        digito = binario[i]
        if digito == '1':
            decimal += potencia
        potencia *= 2
        i -= 1

    return decimal

# Solicitar entrada de usuario
binario = input("Introduce un número binario: ")

# Convertir y mostrar resultado
print("Número decimal:", binario_a_decimal(binario))